<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Foolain\Gt3\Block\Form\Gt3 $block */
?>

<?php
    $gt3IsEnabled = $block->getGt3IsEnabled();
    $gt3ID = $block->getGt3Id();
    $gt3Key = $block->getGt3Key();
?>

<?php if ($block->gt3IsEnabled()): ?>
    <div class="field gt3 required">
        <label for="Captcha" class="label"><span><?= $block->escapeHtml(__('Captcha')) ?></span></label>
        <div class="gt3 gt3-captcha" id="gt3-captcha"></div>
        <p id="wait" class="show">
            <?= $block->escapeHtml(__('Loading Verification Code......')) ?>
        </p>
        <p id="notice" class="hide">
            <?= $block->escapeHtml(__('Please Complete Verification')) ?>
        </p>
    </div>
<?php endif; ?>

<?php if($block->gt3IsEnabled()): ?>
<script type="text/javascript">
require(['jquery', 'gt3'], function($){
    /**
     * Gt3 Captcha
     **/
    var handlerEmbed = function (captchaObj) {
        $(".actions-toolbar .primary button").click(function (e) {
            var validate = captchaObj.getValidate();
            if (!validate) {
                $("#notice")[0].className = "show";
                setTimeout(function () {
                    $("#notice")[0].className = "hide";
                }, 2000);
                e.preventDefault();
            }
        });
        // 将验证码加到id为captcha的元素里，同时会有三个input的值：geetest_challenge, geetest_validate, geetest_seccode
        captchaObj.appendTo("#gt3-captcha");
        captchaObj.onReady(function () {
            $("#wait")[0].className = "hide";
        });
        // 更多接口参考：http://www.geetest.com/install/sections/idx-client-sdk.html
    };
    $.ajax({
        // 获取id，challenge，success（是否启用failback）
        url: "<?php $block->getBaseUrl() ?>/gt3/gt3/initcaptcha?t=" + (new Date()).getTime(), // 加随机数防止缓存
        type: "get",
        dataType: "json",
        success: function (data) {
            console.log(data);
            // 使用initGeetest接口
            // 参数1：配置参数
            // 参数2：回调，回调的第一个参数验证码对象，之后可以使用它做appendTo之类的事件
            initGeetest({
                gt: data.gt,
                challenge: data.challenge,
                new_captcha: data.new_captcha,
                product: "embed", // 产品形式，包括：float，embed，popup。注意只对PC版验证码有效
                offline: !data.success // 表示用户后台检测极验服务器是否宕机，一般不需要关注
                // 更多配置参数请参见：http://www.geetest.com/install/sections/idx-client-sdk.html#config
            }, handlerEmbed);
        }
    });
});
</script>
<?php endif; ?>
